### ISSUE TITLE
RichText field causes blank screen

### ISSUE THREAD

**Issue by mikevarela** [payloadcms/nextjs-custom-server#21]
I've been using this template for a little bit without issues. Then, wanted to create a Post category to blog with. I've created a Collection and added the RichText field. When I attempt to visit the page in the admin panel I get a slew of errors and the screen goes white. If I refresh I can see the page attempting to load for a flash of a second then it goes white again. Doing a little research a few have said it's do to the useMemo function, some mention it's a race condition. Below is the Collection and the error. The error is with Slate. Hoping you might be able to shed some light on the subject. Thanks!!!

```
import { CollectionConfig } from "payload/types";
import titleToSlug from "../fields/titleToSlug";

const Post: CollectionConfig = {
  slug: "posts",
  fields: [
    {
      name: "title",
      label: "Title",
      type: "text",
      required: true,
    },
    {
      name: "summary",
      label: "Summary",
      type: "textarea",
    },
    {
      name: "content",
      label: "Content",
      type: "richText",
      required: true,
    },
    {
      name: "published",
      label: "Published",
      type: "radio",
      options: [
        {
          label: "No",
          value: "no",
        },
        {
          label: "Yes",
          value: "yes",
        },
      ],
      defaultValue: "no",
    },
    {
      name: "categories",
      label: "Categories",
      type: "relationship",
      relationTo: "categories",
      hasMany: true,
    },
    {
      name: "tags",
      label: "Tags",
      type: "relationship",
      relationTo: "tags",
      hasMany: true,
    },
    titleToSlug,
  ],
};

export default Post;
```

------ Error message

```
index.es.js:3909 Uncaught Error: [Slate] editor is invalid! you passed:{"children":[],"operations":[],"selection":null,"marks":null,"history":{"undos":[],"redos":[]}}
    at index.es.js:3909:1
    at mountState (react-dom.development.js:16852:1)
    at Object.useState (react-dom.development.js:17593:1)
    at Object.useState (react.development.js:1620:1)
    at Slate (index.es.js:3903:31)
    at renderWithHooks (react-dom.development.js:16175:1)
    at mountIndeterminateComponent (react-dom.development.js:20913:1)
    at beginWork (react-dom.development.js:22416:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4161:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4210:1)
```

**Comment by jmikrut** [comment]
Hey @mikevarela — do you have a local copy of Slate installed in your package.json?

I believe we've seen this before when there were more than one copies of Slate, with different versions. Will you check that?

**Comment by mikevarela** [comment]
Thanks for getting back to me. I'm using the package json file in the template. I actually deleted the lock file and reinstalled all the packages hoping that might fix it, but problem still exists. Below is the package.json file for reference.

```
 "scripts": {
    "build:next": "next build",
    "build:server": "tsc --project tsconfig.server.json",
    "build:payload": "payload build",
    "build": "cross-env NODE_ENV=production yarn build:payload && yarn build:server && cross-env NEXT_BUILD=true node dist/index.js",
    "dev": "node dev.js",
    "seed": "node seed/index.js",
    "serve": "cross-env NODE_ENV=production node dist/index.js"
  },
  "dependencies": {
    "@babel/register": "^7.17.0",
    "dotenv": "^16.0.0",
    "escape-html": "^1.0.3",
    "express": "^4.18.0",
    "next": "^12.1.0",
    "payload": "^1.0.7",
    "react": "^18.1.0",
    "sass": "^1.52.0",
    "slate": "^0.81.0",
    "typescript": "^4.7.0"
  },
  "devDependencies": {
    "@trbl/eslint-config": "^1.2.4",
    "@types/express": "^4.17.11",
    "@types/react": "^16.9.56",
    "@typescript-eslint/eslint-plugin": "4.0.1",
    "@typescript-eslint/parser": "4.0.1",
    "cross-env": "^7.0.3",
    "eslint": "^7.11.0",
    "eslint-plugin-import": "^2.20.0",
    "eslint-plugin-jest": "^23.16.0",
    "eslint-plugin-jest-dom": "^3.0.1",
    "eslint-plugin-jsx-a11y": "^6.2.1",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-react": "^7.18.0",
    "eslint-plugin-react-hooks": "^2.3.0",
    "ts-node": "^10.8.0"
  }
```
Looking at my node modules folder I see 4 packages for Slate.

slate,
slate-history
slate-hyperscript
slate-react

Does this help?

**Comment by jmikrut** [comment]
Hey @mikevarela of course.

So, this is exactly what's going on. If you look at your `package.json`, you have `"slate": "^0.81.0"` but the `package.json` in this repo is specified as `"slate": "^0.72.8"`.

This was fixed ~20 days ago. If you update your `package.json` to the same as the one in this repo, and then reinstall all modules, you'll be good!

**Comment by mikevarela** [comment]
Magic. Thanks James!
