### ISSUE TITLE
build cannot import buildConfig from payload

### ISSUE THREAD

**Issue by KalebKloppe** [payloadcms/nextjs-custom-server#26]
I cloned a clean copy of this repo and followed the instructions. When building this example for production I run into this same import issue. I have tried it using yarn and npm:

```
npm run build

> payload-nextjs-server@0.0.1 build
> cross-env NODE_ENV=production yarn build:payload && yarn build:server && cross-env NEXT_BUILD=true node dist/index.js

yarn run v1.22.19
$ payload build
Done in 11.19s.
yarn run v1.22.19
$ tsc --project tsconfig.server.json
Done in 1.71s.
[16:32:09] INFO (payload): Connected to Mongo server successfully!
[16:32:09] INFO (payload): Starting Payload...
/home/kaleb/code/nextjs-custom-server/payload.config.ts:1
import { buildConfig } from 'payload/config';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadConfig (/home/kaleb/code/nextjs-custom-server/node_modules/payload/dist/config/load.js:21:18)
    at BasePayload.init (/home/kaleb/code/nextjs-custom-server/node_modules/payload/dist/payload.js:200:27)
```

Rolling back one commit (7697c07b54758d2452dfba65cc10f8dd1462e1f3) successfully builds.

```
npm run build

> payload-nextjs-server@0.0.1 build
> cross-env NODE_ENV=production yarn build:payload && yarn build:server && cross-env NEXT_BUILD=true node dist/index.js

yarn run v1.22.19
$ payload build
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
Done in 14.36s.
yarn run v1.22.19
$ tsc --project tsconfig.server.json
Done in 1.72s.
[16:40:12] INFO (payload): Starting Payload...
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
NextJS is now building...
info  - Loaded env from /home/kaleb/code/nextjs-custom-server/.env
[16:40:13] INFO (payload): Connected to Mongo server successfully!
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
info  - Checking validity of types  
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
warn  - The Next.js plugin was not detected in your ESLint configuration. See https://nextjs.org/docs/basic-features/eslint#migrating-existing-config

./components/RenderBlocks/index.tsx
18:29  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any

./components/RichText/index.tsx
4:56  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
info  - Creating an optimized production build ..webpack built 22e695c0315a2c593476 in 12238ms
webpack compiled successfully
info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data  
info  - Generating static pages (1/1)
info  - Finalizing page optimization  

Page                                       Size     First Load JS
┌ λ /                                      257 B           108 kB
├   /_app                                  0 B            74.9 kB
├ λ /[...slug]                             205 B           108 kB
└ ○ /404                                   304 B          75.2 kB
+ First Load JS shared by all              74.9 kB
  ├ chunks/framework-332b5ae52c2b3ebe.js   45 kB
  ├ chunks/main-513e1be867958890.js        28.6 kB
  ├ chunks/pages/_app-111b1fc4a041b4fc.js  499 B
  ├ chunks/webpack-a5a2c4a385dd3960.js     769 B
  └ css/d1719792463ae015.css               286 B

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
```

npm: 8.11.0
node: v16.15.1
WSL2 / Ubuntu 20.04.5 LTS

**Comment by jpumfrey** [comment]
I also ran into this issue after adding Payload to my T3 stack project. Here's a temporary solution that at least allowed me to run the latest Payload version locally using ts-node which should already be an installed package from this repo:

1. Add ts-node options to tsconfig.json:
`"ts-node": {
    "transpileOnly": true,
    "swc": true
  }`
2. In tsconfig, change `"module": "esnext",` to `"module": "commonjs",`
3. Restart TS server
4. Run Payload using `ts-node --esm server`

**Comment by jmikrut** [comment]
So the issue that is causing the build to fail is that our build script runs the following:

```
node dist/index.js
```

You can see that this is executing the `dist/index.js` file with regular 'ol Node. But, this file will attempt to import the Payload config, which by default, is located at the root of the project as `payload.config.ts`. 

We now no longer transpile configs within Payload, which means that when Node attempts to parse `payload.config.ts`, it will get hung up on the `import` statement. This repo needs to be updated so that in addition to building the _**server**_ for production, that the Payload config itself is also built for production to the `/dist` folder.

Then, the NPM `build` command can be run with `PAYLOAD_CONFIG_PATH=dist/payload.config.js`, which will be safe for regular Node.

We will get to this ASAP. Likely Monday of next week or sooner. But that's the jist of what needs to happen here.

**Comment by JuanSebastianM** [comment]
I tried setting up the solution @jmikrut provided, but now I'm getting this error: 
```
> tsc --project tsconfig.server.json

[23:46:09] INFO (payload): Connected to Mongo server successfully!
[23:46:09] INFO (payload): Starting Payload...
unhandledRejection Error: Cannot find module './index.module.css'
Require stack:
- C:\Users\cebo_\Desktop\Learning\payload-nextjs-practice\dist\src\blocks\Image\index.js
- C:\Users\cebo_\Desktop\Learning\payload-nextjs-practice\dist\src\collections\Page.js
- C:\Users\cebo_\Desktop\Learning\payload-nextjs-practice\dist\payload.config.js
- C:\Users\cebo_\Desktop\Learning\payload-nextjs-practice\node_modules\payload\dist\config\load.js
- C:\Users\cebo_\Desktop\Learning\payload-nextjs-practice\node_modules\payload\dist\payload.js
- C:\Users\cebo_\Desktop\Learning\payload-nextjs-practice\node_modules\payload\dist\initHTTP.js
- C:\Users\cebo_\Desktop\Learning\payload-nextjs-practice\node_modules\payload\dist\index.js
- C:\Users\cebo_\Desktop\Learning\payload-nextjs-practice\dist\server.js
```

This is my `tsconfig.server.json` file:
```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "module": "commonjs",
    "noEmit": false,
    "jsx": "react",
    "outDir": "dist"
  },
  "include": ["./server.ts", "./payload.config.ts"]
}
```

My `dist` folder looks like this after `tsconfig.server.json` is compiled:
![image](https://user-images.githubusercontent.com/84402295/222856617-9c68394b-9b63-4e12-b90f-6b1441bd74e2.png)

I'm not sure why the `src` folder is getting compiled too, I don't know if that's supposed to work like that, but yeah... I'm using the `src` folder in NextJS to store the `pages`, `components`, and everything else...

FYI, I tried creating a `css.d.ts` file to declare a module, but I still get that error.
```
declare module "*.css" {
  const content: Record<string, string>;
  export default content;
}
```

**Comment by ssyberg** [comment]
I just spun up a brand new install with `npx create-payload-app` and I'm also getting this error when running `yarn dev` - any ideas?

**Comment by JarrodMFlesch** [comment]
Hello everyone - I just merged in fixes for the above headaches. When you get time I would love to have you all pull from latest or re-clone and give it a spin. The README setup is the same, but some of the inner workings needed to be adjusted to avoid the CommonJS vs ESM battle here.

Let me know how it goes 👍

**Comment by usluhan-u** [comment]
Hi there,

Thank you for this such a great project!

I've tried to build my project w/ fully re-cloned last commit of yours.
But, I get these errors;

```
yarn run v1.22.19
$ cross-env NODE_ENV=production yarn build:payload && yarn build:server && yarn serve
$ payload build
$ tsc --project tsconfig.server.json
$ cross-env NODE_ENV=production PAYLOAD_CONFIG_PATH=dist/payload.config.js node dist/index.js
node:internal/modules/cjs/loader:1063
  throw err;
  ^

Error: Cannot find module '/Users/usluhan/Desktop/payload/nnv/dist/index.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1060:15)
    at Module._load (node:internal/modules/cjs/loader:905:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

```

I think I am missing some points that need to be done. How can I fix these issues?
Thank you.

**Comment by JarrodMFlesch** [comment]
@in-vp I don't think your repo is up to date with the latest. If you compare it's package.json with yours, I think you will find that the `serve` script is different. 

Your serve script needs to point to `/dist/server.js` but is pointing to `/dist/index.js`

**Comment by usluhan-u** [comment]
> @in-vp I don't think your repo is up to date with the latest. If you compare it's package.json with yours, I think you will find that the `serve` script is different.
> 
> Your serve script needs to point to `/dist/server.js` but is pointing to `/dist/index.js`

I've solved the problems. Thank you so much!
