### ISSUE TITLE
Payload not finding collection when using getStaticPaths

### ISSUE THREAD

**Issue by mooxl** [payloadcms/nextjs-custom-server#27]
When using `getStaticPaths` in Next.js, the payload is not finding the collection. However, `getStaticProps` is working as expected.

### Steps to reproduce

1. Define a collection in your Next.js project
1. Use `getStaticPaths` to generate static paths for the collection
1. Attempt to access the collection trough the Payload Local API

or

1. clone [this respository](https://github.com/mooxl/getStaticPaths-payload)
1. create some news
1. click on link from `/`

### Expected behavior

The payload for the collection should be accessible when using `getStaticPaths`.

### Actual behavior

The payload is not finding the collection when using `getStaticPaths` and gives following error:

```
error - Error [APIError]: The collection with slug news can't be found.
    at new ExtendableError (/Users/max/progg/mediaatrium/nextjs-custom-server/node_modules/payload/dist/errors/APIError.js:22:15)
    at new APIError (/Users/max/progg/mediaatrium/nextjs-custom-server/node_modules/payload/dist/errors/APIError.js:38:9)
    at findLocal (/Users/max/progg/mediaatrium/nextjs-custom-server/node_modules/payload/dist/collections/operations/local/find.js:16:15)
    at BasePayload.find (/Users/max/progg/mediaatrium/nextjs-custom-server/node_modules/payload/dist/payload.js:53:20)
    at getStaticPaths (webpack-internal:///./pages/news/[title].tsx:14:72)
    at Object.buildStaticPaths (/Users/max/progg/mediaatrium/nextjs-custom-server/node_modules/next/dist/build/utils.js:610:39)
    at Object.loadStaticPaths (/Users/max/progg/mediaatrium/nextjs-custom-server/node_modules/next/dist/server/dev/static-paths-worker.js:64:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'APIError',
  status: 500,
  data: null,
  isPublic: false,
  isOperational: true,
  page: '/news/test'
}
```

**Comment by jmikrut** [comment]
Hey there - this is because Next runs `getStaticPaths` in _**another thread**_, meaning even if you have already initialized Payload elswhere, within that function, Payload has not yet been initialized.

If you initialize Payload in that function, you will be all set. Alternatively, you can just use REST or GraphQL straight to your API.

It's certainly a "gotcha" about Next. But we have some new patterns coming out soon that solve this in an elegant way. For now, the above should be what you need.
