### ISSUE TITLE
Error on build with custom view

### ISSUE THREAD

**Issue by enrico-bagattin** [payloadcms/nextjs-custom-server#30]
Hello, I am facing an issue when serving the built project if I use custom views.

I reproduced the problem on a empty project by adding [this custom view](https://github.com/payloadcms/payload/blob/master/test/admin/components/views/CustomMinimal/index.tsx) to the List view of `Page` collection.

The error (after build):

```
yarn run v1.22.19
$ cross-env NODE_ENV=production PAYLOAD_CONFIG_PATH=dist/payload.config.js node dist/server.js
[10:01:54] INFO (payload): Connected to Mongo server successfully!
[10:01:54] INFO (payload): Starting Payload...
unhandledRejection Error: Cannot find module '../components/CustomMinimalView'
Require stack:
- /nextjs-custom-server-master/dist/collections/Page.js
- /nextjs-custom-server-master/dist/payload.config.js
- /nextjs-custom-server-master/node_modules/payload/dist/config/load.js
- /nextjs-custom-server-master/node_modules/payload/dist/payload.js
- /nextjs-custom-server-master/node_modules/payload/dist/initHTTP.js
- /nextjs-custom-server-master/node_modules/payload/dist/index.js
- /nextjs-custom-server-master/dist/server.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
    at Function.mod._resolveFilename (/nextjs-custom-server-master/node_modules/next/dist/build/webpack/require-hook.js:23:32)
    at Function.Module._load (node:internal/modules/cjs/loader:833:27)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/nextjs-custom-server-master/dist/collections/Page.js:11:43)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/nextjs-custom-server-master/dist/collections/Page.js',
    '/nextjs-custom-server-master/dist/payload.config.js',
    '/nextjs-custom-server-master/node_modules/payload/dist/config/load.js',
    '/nextjs-custom-server-master/node_modules/payload/dist/payload.js',
    '/nextjs-custom-server-master/node_modules/payload/dist/initHTTP.js',
    '/nextjs-custom-server-master/node_modules/payload/dist/index.js',
    '/nextjs-custom-server-master/dist/server.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by enrico-bagattin** [comment]
I'm pretty new to typescript but I finally find out what's missing, in the `tsconfig` file there is the `jsx` option set to `preserve`. 
@JarrodMFlesch  Was there a reason for this? 

I can confirm that setting it to `react` the error is no more there.

**Comment by JarrodMFlesch** [comment]
@enrico-bagattin I do believe that `react` is the correct setting. Want to PR that change in?

**Comment by enrico-bagattin** [comment]
Sure!
